### PR TITLE
Add theory for Ninja

### PR DESCRIPTION
**Pull request by meshtag**
This PR intends to add a basic introduction to Ninja build system and a general overview of its syntax. 
(/cc @VedantParanjape )

### CODE REVIEW

**Comment by gautam-dev-maker** [comment]
As there is Example for using CMakeLists , add an example to compile a program using ninja too

**Comment by VedantParanjape** [comment]
@meshtag I appreciate you adding content, but without examples of its own, it really doesn't account much. Please update the examples to match the file names used in Make's examples, as they are real files that have been created in previous content and we expect students to reproduce it on their system, i.e., let Ninja do the same thing that the above Makefile does.

**Comment by meshtag** [comment]
@VedantParanjape , Thanks for the feedback!

> let Ninja do the same thing that the above Makefile does.

Are you pointing to the file present at the end of [this](https://github.com/SRA-VJTI/embedded-systems-study-group/blob/master/week2/week2.md#gnu-make) section?
Btw, I don't think that Makefile will be able to successfully create the desired executable as it doesn't link the object file generated from string_add.c while creating the executable ```library```. 
Was that intentional? or am I missing something here?(Please correct me if latter is the case)

>  Please update the examples to match the file names used in Make's examples, as they are real files that have been created in previous content,

Do you want me to add something like this?
```
rule cc
  command = gcc -c $in -I./include/ -o $out

rule ll
  command = gcc -o $out $in 

build library.o: cc library.c

build main.o: cc main.c

build string_add.o: cc string_add.c

build library: ll library.o string_add.o main.o
```

**Comment by VedantParanjape** [comment]
> @VedantParanjape , Thanks for the feedback!
> 
> > let Ninja do the same thing that the above Makefile does.
> 
> Are you pointing to the file present at the end of [this](https://github.com/SRA-VJTI/embedded-systems-study-group/blob/master/week2/week2.md#gnu-make) section?
> Btw, I don't think that Makefile will be able to successfully create the desired executable as it doesn't link the object file generated from string_add.c while creating the executable

https://github.com/SRA-VJTI/embedded-systems-study-group/blob/master/assets/week2/code1.zip

This is what makefile tries to compile

> Do you want me to add something like this?
Yup !

> ```
> rule cc
>   command = gcc -c $in -I./include/ -o $out
> 
> rule ll
>   command = gcc -o $out $in 
> 
> build library.o: cc library.c
> 
> build main.o: cc main.c
> 
> build string_add.o: cc string_add.c
> 
> build library: ll library.o

**Review by VedantParanjape — APPROVED** [review]

**Pull request merged**
